n = 18
(
    SELECT_LANG,
    GET_NAME,
    GET_CONTACT,
    CLICK_LANG,
    ALL_SETTINGS,
    LANG_SETTINGS,
    NAME_SETTINGS,
    PHONE_SETTINGS,
    GET_PRODUCT_NAME,
    GET_PRODUCT_TYPE,
    GET_PRODUCT_AMOUNT,
    GET_PRODUCT_COMMENT,
    SEARCHING,
    GET_ACTION,
    GET_OBJECT,
    GET_PHOTO,
    FINISH_STATEMENT,
    CLICK_STATEMENT,

) = range(0, n)
